### PR TITLE
[readme] add install instructions

### PR DESCRIPTION
**Pull request by gruns**

### CODE REVIEW

**Review by ljharb — COMMENTED** [review]
I guess this is OK, but if you don't know the foundational basics of how to npm install something, is this package the place someone's likely to first encounter it?

**Comment by gruns** [comment]
I had to exhume `package.json` to determine the name of the package on npm to install, i.e.,

```
"name": "is-callable",
```

The GitHub repo is named `is-callable`, but that's no guarantee that the npm package has the same name. E.g., it could be `iscallable`.

This helps

  1) Gives new `npm` users (we all started somewhere) explicit instructions.
  2) Confirms the name of the package.
  3) Gives users something to copy/paste.

**Comment by ljharb** [comment]
There's a large image at the top of the readme that contains the text `npm install is-callable`. Was that not sufficient?

**Comment by gruns** [comment]
Didn't see that.

My expectation is installation instructions, if any, reside in the readme, not in a banner image. So that's where I looked.

¯\_(ツ)_/¯

**Review by ljharb — APPROVED** [review]
I also expect packages to all be discovered from npm, and not via github, but since this would have helped you, might as well add it.

**Pull request merged**
